# Introduction

Exercise, which is often associated with positive mental and physical health outcomes in the general population (CITE), can also become maladaptive, particularly in the context of disordered eating (CITE). Though definitions of maladaptive exercise vary and many terms have been used to describe this behavior, a broad conceptualization of maladaptive exercise includes exercise that exhibits one or more of the following qualities: a) exercise that is maladaptive or compulsive in nature, b) feelings of distress or guilt arise when an individual is unable to exercise, c) exercise that interferes with one's ability to engage in school, work, or daily activities, d) the inability to refrain from exercise despite circumstances (e.g. illness, injury) in which exercise is not recommended. Such experiences, which indicate that exercise may be functioning in a problematic way, most often arise when individuals also report a primary motivation for engaging in exercise related to weight loss or weight management (CITE). Most concerning, maladaptive exercise may be an early indicator of disordered eating behavior, as retrospective reports of individuals with eating disorders suggest that maladaptive exercise is an early-developing eating disorder feature (CITE), and, once entrenched, maladaptive exercise patterns can be a pernicious and debilitating eating disorder symptom (CITE), and a marker of poor prognosis (CITE). Amongst individuals with eating disorders, maladaptive (and more specifically, compulsive) exercise is a commonly-reported feature of illness, with up to 40% of individuals with bulimia nervosa and 80% of those with anorexia nervosa reporting maladaptive exercise.

Given the risks associated with maladaptive exercise and its potential etiologic relevance in the context of eating disorders, clarification regarding the prevalence and early predictors of high-risk exercise behavior during adolescence could build knowledge necessary to prevent maladaptive exercise patterns from taking hold. Current studies with population-based samples indicate that, for instance, high levels of exercise are associated with higher likelihood of experiencing an eating disorder among adult women (CITE). Further, a previous prospective study in the Avon Longitudinal Study of Parents and Children (ALSPAC) indicated that young people who reported either exercise for weight loss or maladaptive exercise at age 14 were also more likely to report higher concurrent and future (Age 16) eating disorder behaviors [@schaumbergProspectiveAssociationsDriven2022].

While initial evidence suggests that engaging in exercise for weight loss could escalate to maladaptive exercise and trigger eating disorder risk in some cases, additional investigation is necessary to clarify this process, including the frequency with which young people transition to and from maladaptive patterns of exercise. Further, identification of early predictors of maladaptive exercise could aid in identifying at-risk youth.

## Current Study

In the current study, we extend a longitudinal investigation of exercise for weight loss and maladaptive exercise across a developmental window from middle adolescence to young adulthood (ages 14-24). Specifically, we aim to examine the frequency of exercise states, based on the three categories of 'no exercise for weight loss', 'exercise for weight loss', and 'maladaptive exercise', amongst boys and girls at ages 14, 16, 18, and 24. We will examine rates of transitions between these exercise states over time, and identify any preliminary predictors of these transitions. Further, we aim to characterize overall risk for engaging in maladaptive exercise across age, and identify potential demographic or early (age 14) eating disorder cognition variables that may enhance risk for maladaptive exercise. Based on previous literature, we hypothesize that exercise for weight loss will be a common behaivor across adolescence, with maladaptive exercise being less common than exercise for weight loss, but will occur in a sizable minority of adolescnce. Further, we hypothesize that eating disorder cognition assessed at age 14 will be associated with higher likelihood of exercise for weight loss and maladaptive exercise across adolescence. Specific aims are as follows:

**Aim 1:** To investigate rates of transition between 'no exercise for weight loss', 'exercise for weight loss', and 'driven exercise' groups from ages 14-24, and characterize initial predictors of transitions to driven exercise amongst boys and girls.

H1: Maladaptive exercise will be the most stable category, and transitions between the driven exercise and exercise for weight loss categories will be more common than transitions between the driven exercise and no exercise for weight loss category.

**Aim 2:** To examine overall changes in probability of maladaptive exercise and exercise for weight loss from ages 14-24 and characterize initial predictors of changes in probability of maladaptive exercise and exercise for weight loss over time

H2: We have no directional hypotheses regarding parent SES or Age 13 BMI as predictors of maladaptive exercise. We beleive that the prevalence of exercise for weight loss and driven exercise will increase somewhat with age, reflecting transition to peak age of onset for eating disorders across the study period. We hypothesize that ED cognitions at age 14 will predict maladaptive exercise and exercise for weight loss across adolescent and young adult development.

