
## Measures

### Socioeconomic Status

A measure of parent socioeconomic status was obtained during child gestation. 

### Eating Disorder Cognitions

Several eating disorder cognitions were assessed when children were 14 years of age. Relevant eating disorder cognitions for the current analyses are: body dissatisfaction, thin-ideal internalization, and fear of weight gain. 

#### Body Dissatisfaction
Body Dissatisfaction was assessed via an 11-item scale adapted from the satisfaction and dissatisfaction with body parts scale [@sticeProspectiveTestDualpathway2001], and has previously been used in several studies involving the ALSPAC Cohort [@bornioliAdolescentBodyDissatisfaction2019]. Among the 11 items, one item differs between the sexes (satisfaction with 'breasts' is specified for girls and 'build' for boys). Two items address overall body satisfaction with weight and figure, and the remaining items evaluate satisfaction with specific body parts. Responses are graded on a 5 point likert scale from "Extremely Satisfied" (1) to "Extremely Dissatisfied" (5). For the current study, body dissatisfaction is scored using the mean of all items, with  higher scores indicating greater body dissatisfaction.

#### Thin-ideal Internalization

#### Fear of Weight Gain

### Body Mass Index Z-score (BMI-Z)

Child BMI-Z was assessed via two indices at age 13 years. First, objective height and weight were obtained for those who completed a clinic visit at age 13

### Exercise Measures Across Age

Questions related to driven exercise were self-reported at ages 14, 16, 18, and 24 years. Questions were adapted from the Youth Risk Behavior Survelliance System [@kannYouthRiskBehavior1995].

#### Exercise for Weight Loss
At ages 14, 16, and 18 years, individuals were asked if they exercised to lose weight or avoid gaining weight, with response options of: No, Yes-Sometimes, and Yes-Frequently. 

At age 24, individuals were asked the frequency with which they exercised to lose weight or avoid gaining weight, with response options of: Never, <1x/mo, 1-3x/mo, 1-4x/wk, and 5 or more times per week. For the purposes of this analysis, responses at age 24 were harmonized with age 14, 16, and 18.  Responses of Never and <1x/mo were binned as "No";  1x/mo to 4x/wk as 'Yes - Sometimes', and 5x/wk or more as 'Yes - Frequently'. 

#### Exercise Issues
Issues that are associated with exercise were also reported at ages 14,16, 18, and 24 years. At all ages, participants reported whether exercise interferes with work/school (14,16,18), or their daily routine (24). At ages 14 and 24, participants also reported whether they exercised to lose weight even when sick or injured. At ages 16 and 18 years, participants reported whether they felt guilty about missing an exercise session (see Table 1).


Table 1: Exercise Issues Assessed at Ages 14-24

|Age| Interferes| Sick/Injured | Guilt|
|--|--|--|--|
|14| x |x |  |
|16| x |  | x|
|18| x |  | x|
|24| x |x |  |



