
#Mixed Effects Models

## Driven Exercise

### Girls

```{r}
load('models/Girl_Models_DEx')

bl_0_dex_girls_pooled <- pool(bl_0_dex_girls)
bl_0_dex_girls_ORs <- summary(bl_0_dex_girls_pooled, conf.int = TRUE, exponentiate = TRUE) 

bl_0_dex_girls_ORs <- bl_0_dex_girls_ORs |>  
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

age_1_dex_girls_pooled <- pool(age_1_dex_girls)
age_1_dex_girls_ORs <- summary(age_1_dex_girls_pooled, conf.int = TRUE, exponentiate = TRUE)  |> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)


#use the D1 method to compare 
mcomp_1 <- D1(age_1_dex_girls, bl_0_dex_girls)


#Now we include fixed effect covariates of BMI, parent highest occupation, and eating disorder cogitions at age 14: thin-ideal internalization, body dissatisfaction, and fear of weight gain
covs_2_dex_girls_pooled <- pool(covs_2_dex_girls)
covs_2_dex_girls_ORs <- summary(covs_2_dex_girls_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

mcomp_2 <- D1(covs_2_dex_girls, age_1_dex_girls)


covs_3_dex_girls_pooled <- pool(covs_3_dex_girls)
covs_3_dex_girls_ORs <- summary(covs_3_dex_girls_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

mcomp_3 <- D1(covs_3_dex_girls, covs_2_dex_girls)

covs_4_dex_girls_pooled <- pool(covs_4_dex_girls)
covs_4_dex_girls_ORs <- summary(covs_4_dex_girls_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

mcomp_4 <- D1(covs_4_dex_girls, covs_3_dex_girls)

```


```{r, label = 'DEx Poled Coeffs Table - Girls'}

dfnames <- c("bl_0_dex_girls_ORs", "age_1_dex_girls_ORs", 'covs_2_dex_girls_ORs', 'covs_3_dex_girls_ORs', 'covs_4_dex_girls_ORs')
pooled_coefs <- do.call(rbind, lapply(dfnames, function(x) cbind(get(x), Model=x))) |> 
  relocate(Model) %>% 
  select(-c(p.value, statistic, df, `2.5 %`, `97.5 %`))

for (i in 3:ncol(pooled_coefs) ) {
  pooled_coefs[i] <- round(pooled_coefs[i], digits = 3)
}

pooled_coefs['Model'][pooled_coefs['Model'] == 'bl_0_dex_girls_ORs'] <- 'Baseline Model'
pooled_coefs['Model'][pooled_coefs['Model'] == 'age_1_dex_girls_ORs'] <- 'Age Effect Model'
pooled_coefs['Model'][pooled_coefs['Model'] == 'covs_2_dex_girls_ORs'] <- 'Step 1 Covariates'
pooled_coefs['Model'][pooled_coefs['Model'] == 'covs_3_dex_girls_ORs'] <- 'Step 2 Covariates'
pooled_coefs['Model'][pooled_coefs['Model'] == 'covs_4_dex_girls_ORs'] <- 'Step 3 Age x Cov Interactions'

pooled_coefs <- pooled_coefs |> mutate(term = as.character(term))
pooled_coefs['term'][pooled_coefs['term'] == 'parent_highest_occupation'] <- 'Parent SES'
pooled_coefs['term'][pooled_coefs['term'] == 'bmi_z_bestavail'] <- 'BMI Z - Age 13'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust'] <- 'Age'
pooled_coefs['term'][pooled_coefs['term'] == 'fear_wtgain_14'] <- 'Fear of Wt Gain - Age 14'
pooled_coefs['term'][pooled_coefs['term'] == 'body_sat_mean_14_std'] <- 'Body Satisifaction - Age 14'
pooled_coefs['term'][pooled_coefs['term'] == 'ti_mean_14_std'] <- 'Thin-ideal Internalization - Age 14'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:bmi_z_bestavail'] <- 'Age x BMI (13)'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:fear_wtgain_14'] <- 'Age x Fear of Wt Gain (14)'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:body_sat_mean_14_std'] <- 'Age x Body Satisfaction (14)'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:ti_mean_14_std'] <- 'Age x Thin-Ideal Internalization (14)'

est_color <- function (df) {
  if (pooled_coefs$term[i] != '(Intercept)') {
  column_spec(df, 3, color = ifelse(pooled_coefs$estimate > 1, "blue", "red"))}
  else{
  column_spec(df, column = 3, color = 'black')}}

pooled_coefs_girls <- pooled_coefs|> 
  kbl(caption = 'Table 1: Parameter Estimates for Models Predicting Driven Exercise in Girls') %>% 
  row_spec(c(2:3, 8:14), background = '#E0E0E0') %>% 
  column_spec(2:3, color = case_when(pooled_coefs$term != '(Intercept)' & pooled_coefs$`0.25 %` > 1  ~ "blue",
                                   pooled_coefs$term != '(Intercept)' & pooled_coefs$`99.75 %`< 1  ~ "red", 
                                   pooled_coefs$term == '(Intercept)' & pooled_coefs$`0.25 %`> 0 ~ "blue",
                                   pooled_coefs$term == '(Intercept)' & pooled_coefs$`99.75 %`< 0  ~ "red",
                                   TRUE ~ 'black')) |> 
  kable_paper(full_width = T)

pooled_coefs_girls

```

```{r}
#Results Table - Model Comparisons

model_comparisons <- c('mcomp_1', 'mcomp_2', 'mcomp_3', 'mcomp_4')

n = list() 
for (i in model_comparisons) { 
  x<- as.list((eval(ensym(i))[2])) 
  x<- data.frame(t(unlist(x)))
  colnames(x) = c('statistic', 'df1', 'df2', 'p.value','riv')
  n[[i]] = x
}
pooled_coefs_2 <- do.call('rbind', n) 

rownames(pooled_coefs_2) <- c('Baseline vs. Age Effects', 'Age vs. Step 1 Covariates', 'Step 1 vs. Step 2 Covariates', 'Step 2 vs. Age x Covariate Interactions')

mcomp_table_girls <- pooled_coefs_2 %>% 
  kbl(caption = 'Table 2: Model Comparisons - Driven Exercise in Girls', digits = 3) %>% 
  kable_material('striped')

mcomp_table_girls

```

### Boys


```{r}
rm(list = ls())
load('models/Boy_Models_DEx')

```


```{r}

bl_0_dex_boys_pooled <- pool(bl_0_dex_boys)
bl_0_dex_boys_ORs <- summary(bl_0_dex_boys_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

age_1_dex_boys_pooled <- pool(age_1_dex_boys)
age_1_dex_boys_ORs <- summary(age_1_dex_boys_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

#use the D1 method to compare 
mcomp_1 <- D1(age_1_dex_boys, bl_0_dex_boys)

```


```{r}

#Now we include fixed effect covariates of BMI, parent highest occupation, and eating disorder cogitions at age 14: thin-ideal internalization, body dissatisfaction, and fear of weight gain
covs_2_dex_boys_pooled <- pool(covs_2_dex_boys)
covs_2_dex_boys_ORs <- summary(covs_2_dex_boys_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

mcomp_2 <- D1(covs_2_dex_boys, age_1_dex_boys)


covs_3_dex_boys_pooled <- pool(covs_3_dex_boys)
covs_3_dex_boys_ORs <- summary(covs_3_dex_boys_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

mcomp_3 <- D1(covs_3_dex_boys, covs_2_dex_boys)

covs_4_dex_boys_pooled <- pool(covs_4_dex_boys)
covs_4_dex_boys_ORs <- summary(covs_4_dex_boys_pooled, conf.int = TRUE, exponentiate = TRUE)|> 
  mutate(`0.25 %` = estimate - std.error*2.81) |> 
  mutate(`99.75 %` = estimate + std.error*2.81)

mcomp_4 <- D1(covs_4_dex_boys, covs_3_dex_boys)

```




```{r, label = 'DEx Poled Coeffs Table - Boys'}

dfnames <- c("bl_0_dex_boys_ORs", "age_1_dex_boys_ORs", 'covs_2_dex_boys_ORs', 'covs_3_dex_boys_ORs', 'covs_4_dex_boys_ORs')
pooled_coefs <- do.call(rbind, lapply(dfnames, function(x) cbind(get(x), Model=x))) |> 
  relocate(Model) %>% 
  select(-c(p.value, statistic, df, `2.5 %`, `97.5 %`))

for (i in 3:ncol(pooled_coefs) ) {
  pooled_coefs[i] <- round(pooled_coefs[i], digits = 3)
}

pooled_coefs['Model'][pooled_coefs['Model'] == 'bl_0_dex_boys_ORs'] <- 'Baseline Model'
pooled_coefs['Model'][pooled_coefs['Model'] == 'age_1_dex_boys_ORs'] <- 'Age Effect Model'
pooled_coefs['Model'][pooled_coefs['Model'] == 'covs_2_dex_boys_ORs'] <- 'Step 1 Covariates'
pooled_coefs['Model'][pooled_coefs['Model'] == 'covs_3_dex_boys_ORs'] <- 'Step 2 Covariates'
pooled_coefs['Model'][pooled_coefs['Model'] == 'covs_4_dex_boys_ORs'] <- 'Step 3 Age x Cov Interactions'

pooled_coefs <- pooled_coefs |> mutate(term = as.character(term))
pooled_coefs['term'][pooled_coefs['term'] == 'parent_highest_occupation'] <- 'Parent SES'
pooled_coefs['term'][pooled_coefs['term'] == 'bmi_z_bestavail'] <- 'BMI Z - Age 13'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust'] <- 'Age'
pooled_coefs['term'][pooled_coefs['term'] == 'fear_wtgain_14'] <- 'Fear of Wt Gain - Age 14'
pooled_coefs['term'][pooled_coefs['term'] == 'body_sat_mean_14_std'] <- 'Body Satisifaction - Age 14'
pooled_coefs['term'][pooled_coefs['term'] == 'ti_mean_14_std'] <- 'Thin-ideal Internalization - Age 14'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:bmi_z_bestavail'] <- 'Age x BMI (13)'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:fear_wtgain_14'] <- 'Age x Fear of Wt Gain (14)'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:body_sat_mean_14_std'] <- 'Age x Body Satisfaction (14)'
pooled_coefs['term'][pooled_coefs['term'] == 'age_adjust:ti_mean_14_std'] <- 'Age x Thin-Ideal Internalization (14)'


pooled_coefs_boys <- pooled_coefs|> 
  kbl(caption = 'Table 1: Parameter Estimates for Models Predicting Driven Exercise in Boys') %>% 
  row_spec(c(2:3, 8:14), background = '#E0E0E0') %>% 
  column_spec(2:3, color = case_when(pooled_coefs$term != '(Intercept)' & pooled_coefs$`0.25 %` > 1  ~ "blue",
                                   pooled_coefs$term != '(Intercept)' & pooled_coefs$`99.75 %`< 1  ~ "red", 
                                   pooled_coefs$term == '(Intercept)' & pooled_coefs$`0.25 %`> 0 ~ "blue",
                                   pooled_coefs$term == '(Intercept)' & pooled_coefs$`99.75 %`< 0  ~ "red",
                                   TRUE ~ 'black')) |> 
  kable_paper(full_width = T)

pooled_coefs_boys

```



```{r}
#Results Table - Model Comparisons

model_comparisons <- c('mcomp_1', 'mcomp_2', 'mcomp_3', 'mcomp_4')

n = list() 
for (i in model_comparisons) { 
  x<- as.list((eval(ensym(i))[2])) 
  x<- data.frame(t(unlist(x)))
  colnames(x) = c('statistic', 'df1', 'df2', 'p.value','riv')
  n[[i]] = x
}
pooled_coefs_2 <- do.call('rbind', n) 

rownames(pooled_coefs_2) <- c('Baseline vs. Age Effects', 'Age vs. Step 1 Covariates', 'Step 1 vs. Step 2 Covariates', 'Step 2 vs. Age x Covariate Interactions')

mcomp_table_boys <- pooled_coefs_2 %>% 
  kbl(caption = 'Table 2: Model Comparisons - Driven Exercise in boys', digits = 3) %>% 
  kable_material('striped')

mcomp_table_boys

```

