# Discussion

## Transitions Across Exercise Groups

Altogether, transitions between exercise groups was common in both girls and boys. Amongst both boys and girls, stability in all groups was moderate, though, contrary to Hypothesis 1a, stability in the 'no exercise for weight loss' group was highest. As hypothesized (H1b) transitions were more common to and from 'exercise for weight loss' and 'maladaptive exercise' as compared to the 'no exercise for weight loss' and 'maladaptive exercise' group. The moderate rates of transitions suggest that, amongst the population-based sample, intervening on psychological motivations for exercise is possible and could impact progression from adaptive to maladaptive exercise engagement.

## Rates of Exercise for Weight Loss and Maladaptive Exercise over Time 

Overall, individuals in this sample reported engaging in exercise for weight loss and maladaptive exercise at relatively high rates across adolescence. Hypothesis 2a was supported in that endorsement of both exercise for weight loss and maladaptive exercise increased over time. With regards to exercise for weight loss, with about half of men and about two thirds of women reported exercise for weight loss at least once per month, and one third of men and almost half of women reporting exercise for weight loss at least once per week at age 24.The increasing rates of exercise for weight loss across adolescence is of potential concern as previous research in this cohort suggests that exercise for weight loss at age 14 is associated with increased risk of other eating disorder symtpoms [@schaumbergProspectiveAssociationsDriven2022]. Further, this exercise for weight loss appears to be associated with issues for a substantial portion of individuals, including exercise interfering with work, school, and daily activities, exercising for weight loss despite illness or injury, and/or frequently feelings of guilt after missing an exercise session. Further, transitioning from 'exercise for weight loss' to 'maladaptive exercise' is relatively common, and occurs at a higher rate than transitioning from 'no exercise for weight loss' to a 'maladaptive exercise' state. 

One possible interpretation of the increase in exercise for weight loss over time is that the increase in exercise for weight loss at age 24, specifically, is an artifact of different response options at this age. While it is possible that the variation in response options at this timepoint influenced rates of endoresment, exercise for weight loss also increased steadily for girls between ages 14-18, suggesting that this interpretation does not fully capture the increase in exercise for weight loss across development. A second interpretation of this increase is that, at younger ages, children are more likely to be actively involved in sports and structured exercise programs and are not motivated by weight management; however, weight loss could transition to be a primary motivator for exercise engagement as organized sport participation wanes in later adolescence. The high rates of endorsement of weight loss as a motivator for exercise appear to eclipse rates of excess weight gain during this time period (CITE), suggesting that the growing weight loss motivation for exercise is not exclusive to those for whom weight loss may have been medically prescribed. The high rates of endorsement of a weight loss motivation for exercise amongst adolescents and young adults in this sample suggests that the experience of exercise may be 'linked' with weight management, and increasingly so, across adolescent development in this Western cohort. The pairing of exercise and weight management, while generally considered innocucous or even beneficial (CITE), may be problematic on a population scale in that: (1) while it can play a role in wight loss maintenance, exercise is not generally an effective weight loss strategy (CITE), (2) weight loss is not indicated for the high percentage of the adolescent population endorsing this motivation (CITE), (3) a focus on weight loss may mean that other, non-weight oriented, motivations and reinforcers associated with exercise could diminish in potenency over time, and (4) exercise for weight loss could lead to maladaptive exercise patterns, and potentially exacerbate eating disorder risk, amongst high-risk youth.  

## Predictors of Maladaptive Exercise

### Eating Disorder Cognitions

With regards to predictors of maladaptive exercise, as expected (Hypothesis 2c), eating disorder cognitions at age 14 predicted increased odds for exercise for weight loss and maladaptive exercise across adolescent and young adult development. The most consistent and strongest cognitive predictor of exercise behavior during this period was fear of weight gain. Recent studies have highlighted the potential etiological centrality of fear of weight gain in eating disorder development, and this finding undorscores this cogntive feature as particularly xx (CITE CHERI AND LEIGH; LOOK UP OLD EXERCISE PAPER; ANXIETY PREDICTION PAPER)

In addition to fear of weight gain, thin-ideal internalization xxx

Of note, body dissatisfaction, was not a consistent predictor, only showing prediction of xxx.  

### Age 13 BMI

While there were no a priori hypotheses regarding BMI as a predictor of maladaptive exercise, BMI Z-score at age 13 was consistently, positively associated with both odds of exercise for weight loss and maladaptive exericse in the cohort. Further, BMI Z-score at age 13 related to increased odds of transitioning from the 'no exericse for weight loss' group to the 'exercise for weight loss' group over time. On the one hand, it is possible that individuals at higher BMIs are both receiving and internalizing messages from media, peers, and health professionals to utilize exercise for weight loss. However, the association with not only exercise for weight loss but also maladaptive exercise suggests that these efforts are not always leading to exercise behavior that is exclusively innocucous or health promoting, and that individuals living in larger bodies may be susceptible to the development of a psychologically problematic relationship with exercise. 

## Limitations 

### Data harmonization across age

As mentioned previously, a first limitation of analyses were slightly different response options at varying ages. Data harmonization in the current study was informed by the existing literature on maladaptive exercise; however, complete harmonization across age was not possible, and may influence endorsement of exercise for weight loss and maladaptive exercise symptoms across age. 

### Assessment gap between 18-24 years

Second, while individuals provided data every two years from ages 14-18, there was a longer gap between measurements from ages 18 to 24 years. The time period between assessments was modeled reflecting real time in both analytic approaches; however, this larger gap leaves some question as to the nature of change in exercise patterns during transition to young adulthood.

### Model Convergence for Transition Models

Third, while maladaptive exercise was present in both boys and girls as individuals transitioned to young adulthood, it was fairly uncommon (< 7% endorsement) amongst boys at younger ages. Due to lower levels of endoresment at younger ages along with relatively few assessment points present per individual, there was low power to examine predictors of transitions to and from driven exercise amongst boys. 

### Snapshot of Anglo-Western Culture

Fourth, while relatively rich information about exercise cognitions across development in this cohort provides a snapshot of the prevalence of maladaptive exercise behaviors, this snapshot is necessarily contextualized in time and place, specifically, in a Western culture with primarily White individuals in the early 21st century. It is likely that rates of exercise for weight loss and maladaptive exercise vary in other adolescent populations. 

## Future Directions

The current paper lays groundwork for continuing to untangle distinctions between adaptive and maladaptive exerise behavior in adolescence. First, while initial work suggests that both exercise for weight loss and maladaptive exercise at age 14 are associated with concurrent and future (age 16) eating disorder behaviors, it is unclear whether this association persists across adolescece, or whether exercise for weight loss continues to demonstrate cross-sectional and longitudinal associations with eating disorder risk as young people age. It is possible, for instance, that exercise for weight loss is most concerning at earlier periods of development. Second, it remins unclear the degree to which psychological motivations for exercise and maladaptive exercise symptoms associate with objective exercise behavior (frequency, intensity of exercise). *frequency or intensity early predicts maladpative OR maladaptive predicts increasing freq/intensity indicating excess OR psychological relationship disagregates from freq** Finally, examination of prospective associations between maladaptive exercise and BMI would clarify the degree to which exercise impacts weight trajectory in a population of adolescence, including potenital growth curve deviations that may signal disordered eating. 

## Conclusions

Building off of initial work examining endorsement of exercise for weight loss and maladaptive exercise in early adolescence, the current study is the first investigation to examine rates of exercise for weight loss and maladaptive exercise longitudinally through adolescent and young adult development. Findings highlight the high and increasing rates of both across adolescence, and bring to question the degree to which marketing and public health messages associating exercise with weight loss may impact young people's experiences of exercise as they age. Further, those who are cognitively at risk for eating disorder development may be most likely to internalize weight loss  motivations for exercise. Given that eating disorder research suggests the psychological components of, rather than frequency and intensity of, exercise are potentially most damaging, focus on 'unpairing' exercise from weight loss motivations at a population level amongst teens and young adults may be indicated. 

